import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Send, X, MessageCircle, Bot, ChevronRight, Loader2 } from 'lucide-react';
import { useTheme } from '../contexts/ThemeContext';

// Define types for chat messages
interface ChatMessage {
  id: string;
  content: string;
  role: 'user' | 'bot';
  timestamp: Date;
}

// Example bot responses based on user queries
const getBotResponse = (query: string): Promise<string> => {
  // Convert query to lowercase for easier matching
  const q = query.toLowerCase();
  
  // Simulate network delay
  return new Promise((resolve) => {
    setTimeout(() => {
      // Automata theory related responses
      if (q.includes('dfa') || q.includes('deterministic finite automaton')) {
        resolve('A Deterministic Finite Automaton (DFA) is a finite state machine that accepts or rejects strings of symbols. In a DFA, for each state and input symbol, there is exactly one transition to a next state. DFAs recognize exactly the regular languages, which are the simplest class in the Chomsky hierarchy.');
      } else if (q.includes('nfa') || q.includes('non-deterministic')) {
        resolve('A Non-deterministic Finite Automaton (NFA) is similar to a DFA but can have multiple possible transitions for a given input symbol from a particular state, or it can have epsilon (empty string) transitions. Despite this added flexibility, NFAs recognize exactly the same languages as DFAs and can always be converted to equivalent DFAs (though this may result in an exponential increase in the number of states).');
      } else if (q.includes('pda') || q.includes('pushdown')) {
        resolve('A Pushdown Automaton (PDA) is a finite automaton that can use a stack to store data. This additional memory makes PDAs more powerful than finite automata, allowing them to recognize context-free languages. PDAs are equivalent in power to context-free grammars. A key example of what PDAs can recognize (that finite automata cannot) is the language of palindromes or the language of matching parentheses.');
      } else if (q.includes('turing')) {
        resolve('A Turing Machine is a mathematical model of computation that defines an abstract machine, which manipulates symbols on a strip of tape according to a table of rules. It has unlimited memory capacity and can simulate any computer algorithm. Turing machines are much more powerful than DFAs or PDAs and can recognize recursively enumerable languages. The Church-Turing thesis posits that any "effectively calculable function" can be computed by a Turing machine.');
      } else if (q.includes('regular expression') || q.includes('regex')) {
        resolve('Regular expressions are patterns used to match character combinations in strings. In automata theory, they precisely define the regular languages, which are recognized by finite automata. A regular expression consists of constants (symbols from the alphabet), operators for union (+), concatenation (juxtaposition), and Kleene star (*) operations. For example, (a+b)* represents all strings consisting of any number of a\'s and b\'s in any order.');
      } else if (q.includes('grammar') || q.includes('cfg') || q.includes('context-free')) {
        resolve('Context-Free Grammar (CFG) is a formal grammar whose production rules can be applied regardless of the context of a nonterminal. They are more powerful than regular languages and can be recognized by pushdown automata. CFGs are commonly used to describe programming languages syntax. The Chomsky Normal Form (CNF) is a simplified form of CFGs where all production rules are of the form A → BC or A → a, making them useful for parsing algorithms like CYK.');
      } else if (q.includes('regular language')) {
        resolve('A regular language is a formal language that can be defined by a regular expression or recognized by a finite automaton. Regular languages are closed under union, intersection, complement, concatenation, and Kleene star operations. Some examples of regular languages include "all strings containing an even number of 0s" or "all strings ending with 01". The pumping lemma for regular languages provides a way to prove that certain languages are not regular.');
      } else if (q.includes('context-free language')) {
        resolve('A context-free language is a language generated by a context-free grammar or recognized by a pushdown automaton. Context-free languages are more powerful than regular languages but less powerful than context-sensitive languages. They can express nested structures like balanced parentheses, which regular languages cannot. The pumping lemma for context-free languages can be used to prove that a language is not context-free.');
      } else if (q.includes('chomsky hierarchy')) {
        resolve('The Chomsky hierarchy is a containment hierarchy of classes of formal grammars that generate formal languages. From most restrictive to least restrictive, it includes: Regular languages (Type 3), Context-free languages (Type 2), Context-sensitive languages (Type 1), and Recursively enumerable languages (Type 0). Each class properly contains the class before it, meaning every regular language is context-free, but not vice versa.');
      } else if (q.includes('pumping lemma')) {
        resolve('The pumping lemma is a property of formal languages that provides a necessary condition for a language to be of a certain type. There are pumping lemmas for regular languages and context-free languages. They are primarily used to prove that certain languages are not regular or not context-free by showing that they violate the necessary condition stated by the relevant pumping lemma.');
      } else if (q.includes('minimize') || q.includes('minimization')) {
        resolve('DFA minimization is the process of transforming a given deterministic finite automaton (DFA) into an equivalent DFA with the minimum number of states. The most common algorithm for DFA minimization is the Hopcroft\'s algorithm, which works by iteratively refining a partition of states according to their behavior. Minimizing a DFA can greatly improve the efficiency of language recognition.');
      } 
      // Website usage help
      else if (q.includes('how to use') || q.includes('help')) {
        resolve('To use our Automata Visualizer, select a regular expression from the list, then click on one of the visualization icons (DFA, CFG, or PDA) to view its corresponding visualization. For DFA, you can validate strings by entering them in the text area below and clicking "Validate All". You can also use the step-by-step simulation to see how the automaton processes each input symbol.');
      } else if (q.includes('create') || q.includes('fsm creator')) {
        resolve('You can create your own Finite State Machine by visiting the FSM Creator page. There, you can add states and transitions, set initial and final states, and see a visual representation of your machine as you build it. You can also export your creation as an image or save it for later use.');
      } else if (q.includes('validate') || q.includes('string') || q.includes('test')) {
        resolve('To validate a string against a DFA, first select a regular expression, then click on the DFA icon to view the DFA visualization. Below the visualization, you\'ll find a textarea where you can enter strings (one per line) to validate. Click the "Validate All" button to see which strings are accepted by the DFA. You can also click "Simulate" next to each string to see a step-by-step animation of the validation process.');
      } else if (q.includes('dark mode') || q.includes('light mode') || q.includes('theme')) {
        resolve('You can toggle between dark mode and light mode by clicking the theme toggle button in the top right corner of the screen. Your preference will be saved for future visits.');
      }
      // General queries
      else if (q.includes('hello') || q.includes('hi') || q.includes('hey')) {
        resolve('Hello! I\'m your Automata Theory assistant. How can I help you today? You can ask me about automata theory concepts like DFAs, NFAs, PDAs, or how to use our tools.');
      } else if (q.includes('thank')) {
        resolve('You\'re welcome! If you have any more questions about automata theory or our tools, feel free to ask. I\'m here to help you understand these concepts better.');
      } else if (q.includes('example')) {
        resolve('Here\'s an example: Consider the regular language "all strings that end with 01". A DFA for this language would have 3 states: a start state, a state after seeing 0, and an accepting state after seeing 1. You can visualize and test this using our tools!');
      } else if (q.includes('who made') || q.includes('developer') || q.includes('creator')) {
        resolve('This Automata Visualizer was created by a team of computer science students from De La Salle University - Dasmariñas. You can learn more about the team on the "Team" page.');
      } else {
        resolve('I\'m not sure about that. Could you ask something specific about automata theory, finite state machines, or how to use our tools? For example, you can ask about DFAs, NFAs, PDAs, Turing Machines, or how to validate strings against automata.');
      }
    }, Math.random() * 500 + 500); // Random delay between 500-1000ms for more natural feel
  });
};

const ChatBot: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: '1',
      content: 'Hello! I\'m your Automata Theory assistant. Ask me anything about automata theory, finite state machines, or how to use our tools.',
      role: 'bot',
      timestamp: new Date()
    }
  ]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [hasShownWelcome, setHasShownWelcome] = useState(false);
  const [hasUnreadMessage, setHasUnreadMessage] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const { theme } = useTheme();

  // Show welcome message after a delay
  useEffect(() => {
    // Show welcome bubble after 3 seconds if user hasn't interacted yet
    const timer = setTimeout(() => {
      if (!hasShownWelcome && !isOpen) {
        setHasShownWelcome(true);
        
        // Flash the chat button with subtle animation
        const bubbleAnimation = document.createElement('div');
        bubbleAnimation.className = 'absolute inset-0 rounded-full bg-white dark:bg-indigo-300 animate-ping opacity-75';
        
        const chatButton = document.querySelector('.chat-button-container');
        if (chatButton) {
          chatButton.appendChild(bubbleAnimation);
          
          // Remove the animation after it plays
          setTimeout(() => {
            if (bubbleAnimation.parentNode === chatButton) {
              chatButton.removeChild(bubbleAnimation);
            }
          }, 2000);
        }
      }
    }, 3000);
    
    return () => clearTimeout(timer);
  }, [hasShownWelcome, isOpen]);

  // Reset unread message indicator when chat is opened
  useEffect(() => {
    if (isOpen) {
      setHasUnreadMessage(false);
    }
  }, [isOpen]);
  
  // Mark messages as unread when new bot messages arrive while chat is closed
  useEffect(() => {
    if (!isOpen && messages.length > 1) {
      const lastMessage = messages[messages.length - 1];
      if (lastMessage.role === 'bot') {
        setHasUnreadMessage(true);
      }
    }
  }, [messages, isOpen]);

  // Scroll to bottom when new messages are added
  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    if (isOpen) {
      scrollToBottom();
    }
  }, [messages, isOpen]);

  // Handle user message submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!inputValue.trim()) return;
    
    // Add user message
    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      content: inputValue,
      role: 'user',
      timestamp: new Date()
    };
    
    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    
    // Show typing indicator
    setIsTyping(true);
    
    try {
      // Get bot response
      const botResponse = await getBotResponse(inputValue);
      
      // Add bot response
      const botMessage: ChatMessage = {
        id: (Date.now() + 1).toString(),
        content: botResponse,
        role: 'bot',
        timestamp: new Date()
      };
      
      setMessages(prev => [...prev, botMessage]);
    } catch (error) {
      // Handle error
      const errorMessage: ChatMessage = {
        id: (Date.now() + 1).toString(),
        content: 'Sorry, I encountered an error processing your request.',
        role: 'bot',
        timestamp: new Date()
      };
      
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsTyping(false);
    }
  };

  // Format time for message timestamp
  const formatTime = (date: Date) => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  return (
    <div className="fixed bottom-6 right-6 z-50">
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.8 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.8 }}
            transition={{
              type: 'spring',
              stiffness: 400,
              damping: 30
            }}
            className={`w-80 sm:w-96 h-[30rem] flex flex-col rounded-2xl shadow-xl overflow-hidden ${
              theme === 'dark' 
                ? 'bg-gray-800 border border-gray-700' 
                : 'bg-white border border-gray-200'
            }`}
          >
            {/* Chatbot Header */}
            <div className={`p-4 flex justify-between items-center ${
              theme === 'dark' ? 'bg-gray-900' : 'bg-gradient-to-r from-indigo-600 to-purple-600'
            }`}>
              <div className="flex items-center space-x-2">
                <Bot className="h-6 w-6 text-white" />
                <h3 className="text-lg font-semibold text-white">Automata Assistant</h3>
              </div>
              <button 
                onClick={() => setIsOpen(false)} 
                className="text-white hover:text-gray-200 transition-colors"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
            
            {/* Messages Container */}
            <div className={`flex-1 overflow-y-auto p-4 ${theme === 'dark' ? 'bg-gray-800' : 'bg-gray-50'}`}>
              {messages.map(message => (
                <motion.div
                  key={message.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3 }}
                  className={`mb-4 flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  <div className={`max-w-[80%] rounded-2xl px-4 py-2 ${
                    message.role === 'user' 
                      ? theme === 'dark' 
                        ? 'bg-indigo-600 text-white' 
                        : 'bg-indigo-500 text-white' 
                      : theme === 'dark' 
                        ? 'bg-gray-700 text-gray-100' 
                        : 'bg-white text-gray-800 border border-gray-200'
                  }`}>
                    <p className="text-sm break-words">{message.content}</p>
                    <div className={`text-xs mt-1 ${
                      message.role === 'user' 
                        ? theme === 'dark' ? 'text-indigo-200' : 'text-indigo-100' 
                        : theme === 'dark' ? 'text-gray-400' : 'text-gray-500'
                    }`}>
                      {formatTime(message.timestamp)}
                    </div>
                  </div>
                </motion.div>
              ))}
              
              {/* Typing indicator */}
              {isTyping && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex justify-start mb-4"
                >
                  <div className={`rounded-2xl px-4 py-2 ${
                    theme === 'dark' ? 'bg-gray-700 text-gray-100' : 'bg-white text-gray-800 border border-gray-200'
                  }`}>
                    <div className="flex items-center space-x-2">
                      <div className="w-2 h-2 rounded-full bg-gray-400 animate-bounce" 
                           style={{ animationDelay: '0ms' }}></div>
                      <div className="w-2 h-2 rounded-full bg-gray-400 animate-bounce" 
                           style={{ animationDelay: '150ms' }}></div>
                      <div className="w-2 h-2 rounded-full bg-gray-400 animate-bounce" 
                           style={{ animationDelay: '300ms' }}></div>
                    </div>
                  </div>
                </motion.div>
              )}
              
              <div ref={messagesEndRef} />
            </div>
            
            {/* Input Area */}
            <form 
              onSubmit={handleSubmit}
              className={`p-3 border-t ${theme === 'dark' ? 'border-gray-700 bg-gray-800' : 'border-gray-200 bg-white'}`}
            >
              <div className="flex space-x-2">
                <input
                  type="text"
                  value={inputValue}
                  onChange={e => setInputValue(e.target.value)}
                  placeholder="Ask something about automata theory..."
                  className={`flex-1 py-2 px-3 rounded-full focus:outline-none ${
                    theme === 'dark' 
                      ? 'bg-gray-700 text-white border border-gray-600 focus:border-indigo-500' 
                      : 'bg-gray-100 text-gray-800 border border-gray-300 focus:border-indigo-400'
                  }`}
                />
                <button 
                  type="submit"
                  disabled={!inputValue.trim() || isTyping}
                  className={`p-2 rounded-full transition-colors ${
                    inputValue.trim() && !isTyping
                      ? theme === 'dark'
                        ? 'bg-indigo-600 hover:bg-indigo-700 text-white'
                        : 'bg-indigo-500 hover:bg-indigo-600 text-white'
                      : theme === 'dark'
                        ? 'bg-gray-700 text-gray-400'
                        : 'bg-gray-200 text-gray-400'
                  }`}
                >
                  {isTyping ? 
                    <Loader2 className="h-5 w-5 animate-spin" /> : 
                    <Send className="h-5 w-5" />
                  }
                </button>
              </div>
            </form>
          </motion.div>
        )}
      </AnimatePresence>
      
      {/* Toggle Button */}
      <motion.button
        onClick={() => setIsOpen(!isOpen)}
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        className={`
          ${isOpen ? 'hidden' : 'flex'} 
          chat-button-container
          relative
          items-center justify-center 
          h-14 w-14 rounded-full shadow-lg 
          ${theme === 'dark' ? 'bg-indigo-600' : 'bg-gradient-to-r from-indigo-600 to-purple-600'}
          text-white
        `}
      >
        {hasUnreadMessage && (
          <span className="absolute top-0 right-0 h-3 w-3 rounded-full bg-red-500 animate-pulse"></span>
        )}
        <motion.div
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
        >
          <MessageCircle className="h-6 w-6" />
        </motion.div>
      </motion.button>
    </div>
  );
};

export default ChatBot; 